version: "3.7"
services:
  mongodb:
    image: mongo:6-jammy
    container_name: "mongodb"
    environment:
      - TZ="Europe/Berlin"
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - db_data:/data/db
      - ./init.d:/docker-entrypoint-initdb.d 
    ports:
      - 27017:27017
    networks:
      - data-network
    healthcheck:
      test: sleep 10; netstat -an | grep 27017 >/dev/null; if [[ 0 != $$? ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  data-network:
    driver: bridge

volumes:
  db_data: